
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."create_new_user_profile"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$BEGIN
  INSERT INTO public.profiles (email, uid, role)
  VALUES (NEW.email, NEW.id, 3);
  RETURN NEW;
END;$$;

ALTER FUNCTION "public"."create_new_user_profile"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."services_categories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "icon" bigint,
    "title_ro" "text",
    "title_ru" "text"
);

ALTER TABLE "public"."services_categories" OWNER TO "postgres";

ALTER TABLE "public"."services_categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title_ro" "text",
    "title_ru" "text",
    "date" "text",
    "place_url" "text",
    "link" "text",
    "place_ru" "text",
    "place_ro" "text",
    "emoji" "text",
    "info_url" "text",
    "paid" boolean
);

ALTER TABLE "public"."events" OWNER TO "postgres";

ALTER TABLE "public"."events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."news" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title_ro" "text",
    "title_ru" "text",
    "description_ro" "text",
    "description_ru" "text",
    "image" "text"
);

ALTER TABLE "public"."news" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."news_comments" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "message" "text",
    "reply_comment_id" bigint,
    "created_by" bigint,
    "likes" "text" DEFAULT '0'::"text",
    "new_id" bigint
);

ALTER TABLE "public"."news_comments" OWNER TO "postgres";

ALTER TABLE "public"."news_comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."news_comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."news_comments_likes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user" bigint,
    "comment" bigint
);

ALTER TABLE "public"."news_comments_likes" OWNER TO "postgres";

ALTER TABLE "public"."news_comments_likes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."news_comments_likes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."news" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."news_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "created_by" bigint,
    "message_key" "text"
);

ALTER TABLE "public"."notifications" OWNER TO "postgres";

ALTER TABLE "public"."notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nick" "text",
    "avatar" "text" DEFAULT ''::"text",
    "role" bigint,
    "uid" "uuid",
    "email" "text"
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

ALTER TABLE "public"."profiles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."profiles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."roles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text"
);

ALTER TABLE "public"."roles" OWNER TO "postgres";

ALTER TABLE "public"."roles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."roles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."services" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title_ru" "text",
    "title_ro" "text",
    "description_ro" "text",
    "description_ru" "text",
    "phone" "text",
    "message" "text",
    "website" "text",
    "category" bigint,
    "place" "text",
    "logo" "text",
    "owner" bigint
);

ALTER TABLE "public"."services" OWNER TO "postgres";

ALTER TABLE "public"."services" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."service_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."services_alerts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description_ru" "text",
    "description_ro" "text",
    "end_date" "text",
    "service" bigint,
    "start_date" "text"
);

ALTER TABLE "public"."services_alerts" OWNER TO "postgres";

ALTER TABLE "public"."services_alerts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."services_alerts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."services_discounts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "start_date" "text",
    "end_date" "text",
    "description_ro" "text",
    "description_ru" "text",
    "service" bigint
);

ALTER TABLE "public"."services_discounts" OWNER TO "postgres";

ALTER TABLE "public"."services_discounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."services_discounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."services_infos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description_ru" "text",
    "description_ro" "text",
    "end_date" "text",
    "start_date" "text",
    "service" bigint
);

ALTER TABLE "public"."services_infos" OWNER TO "postgres";

ALTER TABLE "public"."services_infos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."services_infos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."services_prices" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "service_name_ru" "text",
    "service_name_ro" "text",
    "price" "text"
);

ALTER TABLE "public"."services_prices" OWNER TO "postgres";

ALTER TABLE "public"."services_prices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."services_prices_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."services_categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."news_comments_likes"
    ADD CONSTRAINT "news_comments_likes_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."news_comments"
    ADD CONSTRAINT "news_comments_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."news"
    ADD CONSTRAINT "news_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."roles"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."services"
    ADD CONSTRAINT "service_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."services_alerts"
    ADD CONSTRAINT "services_alerts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."services_discounts"
    ADD CONSTRAINT "services_discounts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."services_infos"
    ADD CONSTRAINT "services_infos_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."services_prices"
    ADD CONSTRAINT "services_prices_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."news_comments"
    ADD CONSTRAINT "news_comments_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."news_comments_likes"
    ADD CONSTRAINT "news_comments_likes_comment_fkey" FOREIGN KEY ("comment") REFERENCES "public"."news_comments"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."news_comments_likes"
    ADD CONSTRAINT "news_comments_likes_user_fkey" FOREIGN KEY ("user") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."news_comments"
    ADD CONSTRAINT "news_comments_new_id_fkey" FOREIGN KEY ("new_id") REFERENCES "public"."news"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_role_fkey" FOREIGN KEY ("role") REFERENCES "public"."roles"("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_uid_fkey" FOREIGN KEY ("uid") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."services_alerts"
    ADD CONSTRAINT "services_alerts_service_fkey" FOREIGN KEY ("service") REFERENCES "public"."services"("id");

ALTER TABLE ONLY "public"."services"
    ADD CONSTRAINT "services_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."services_categories"("id");

ALTER TABLE ONLY "public"."services_discounts"
    ADD CONSTRAINT "services_discounts_service_fkey" FOREIGN KEY ("service") REFERENCES "public"."services"("id");

ALTER TABLE ONLY "public"."services_infos"
    ADD CONSTRAINT "services_infos_service_fkey" FOREIGN KEY ("service") REFERENCES "public"."services"("id");

ALTER TABLE ONLY "public"."services"
    ADD CONSTRAINT "services_owner_fkey" FOREIGN KEY ("owner") REFERENCES "public"."profiles"("id");

CREATE POLICY "Enable read access for all users" ON "public"."news" FOR SELECT USING (true);

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."create_new_user_profile"() TO "anon";
GRANT ALL ON FUNCTION "public"."create_new_user_profile"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."create_new_user_profile"() TO "service_role";

GRANT ALL ON TABLE "public"."services_categories" TO "anon";
GRANT ALL ON TABLE "public"."services_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."services_categories" TO "service_role";

GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."events" TO "anon";
GRANT ALL ON TABLE "public"."events" TO "authenticated";
GRANT ALL ON TABLE "public"."events" TO "service_role";

GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."news" TO "anon";
GRANT ALL ON TABLE "public"."news" TO "authenticated";
GRANT ALL ON TABLE "public"."news" TO "service_role";

GRANT ALL ON TABLE "public"."news_comments" TO "anon";
GRANT ALL ON TABLE "public"."news_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."news_comments" TO "service_role";

GRANT ALL ON SEQUENCE "public"."news_comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."news_comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."news_comments_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."news_comments_likes" TO "anon";
GRANT ALL ON TABLE "public"."news_comments_likes" TO "authenticated";
GRANT ALL ON TABLE "public"."news_comments_likes" TO "service_role";

GRANT ALL ON SEQUENCE "public"."news_comments_likes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."news_comments_likes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."news_comments_likes_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."news_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";

GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";

GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."profiles_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."roles" TO "anon";
GRANT ALL ON TABLE "public"."roles" TO "authenticated";
GRANT ALL ON TABLE "public"."roles" TO "service_role";

GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."services" TO "anon";
GRANT ALL ON TABLE "public"."services" TO "authenticated";
GRANT ALL ON TABLE "public"."services" TO "service_role";

GRANT ALL ON SEQUENCE "public"."service_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."service_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."service_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."services_alerts" TO "anon";
GRANT ALL ON TABLE "public"."services_alerts" TO "authenticated";
GRANT ALL ON TABLE "public"."services_alerts" TO "service_role";

GRANT ALL ON SEQUENCE "public"."services_alerts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."services_alerts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."services_alerts_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."services_discounts" TO "anon";
GRANT ALL ON TABLE "public"."services_discounts" TO "authenticated";
GRANT ALL ON TABLE "public"."services_discounts" TO "service_role";

GRANT ALL ON SEQUENCE "public"."services_discounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."services_discounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."services_discounts_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."services_infos" TO "anon";
GRANT ALL ON TABLE "public"."services_infos" TO "authenticated";
GRANT ALL ON TABLE "public"."services_infos" TO "service_role";

GRANT ALL ON SEQUENCE "public"."services_infos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."services_infos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."services_infos_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."services_prices" TO "anon";
GRANT ALL ON TABLE "public"."services_prices" TO "authenticated";
GRANT ALL ON TABLE "public"."services_prices" TO "service_role";

GRANT ALL ON SEQUENCE "public"."services_prices_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."services_prices_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."services_prices_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
