create table "public"."news_categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title_ru" text,
    "title_ro" text
);


alter table "public"."news" add column "category" bigint;

alter table "public"."news" add column "images" text;

CREATE UNIQUE INDEX news_categories_pkey ON public.news_categories USING btree (id);

alter table "public"."news_categories" add constraint "news_categories_pkey" PRIMARY KEY using index "news_categories_pkey";

alter table "public"."news" add constraint "news_category_fkey" FOREIGN KEY (category) REFERENCES news_categories(id) not valid;

alter table "public"."news" validate constraint "news_category_fkey";

grant delete on table "public"."news_categories" to "anon";

grant insert on table "public"."news_categories" to "anon";

grant references on table "public"."news_categories" to "anon";

grant select on table "public"."news_categories" to "anon";

grant trigger on table "public"."news_categories" to "anon";

grant truncate on table "public"."news_categories" to "anon";

grant update on table "public"."news_categories" to "anon";

grant delete on table "public"."news_categories" to "authenticated";

grant insert on table "public"."news_categories" to "authenticated";

grant references on table "public"."news_categories" to "authenticated";

grant select on table "public"."news_categories" to "authenticated";

grant trigger on table "public"."news_categories" to "authenticated";

grant truncate on table "public"."news_categories" to "authenticated";

grant update on table "public"."news_categories" to "authenticated";

grant delete on table "public"."news_categories" to "service_role";

grant insert on table "public"."news_categories" to "service_role";

grant references on table "public"."news_categories" to "service_role";

grant select on table "public"."news_categories" to "service_role";

grant trigger on table "public"."news_categories" to "service_role";

grant truncate on table "public"."news_categories" to "service_role";

grant update on table "public"."news_categories" to "service_role";