
create table "public"."transport_cities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title_ru" text,
    "title_ro" text,
    "alias" text
);


CREATE UNIQUE INDEX transport_cities_pkey ON public.transport_cities USING btree (id);

alter table "public"."transport_cities" add constraint "transport_cities_pkey" PRIMARY KEY using index "transport_cities_pkey";

grant delete on table "public"."transport_cities" to "anon";

grant insert on table "public"."transport_cities" to "anon";

grant references on table "public"."transport_cities" to "anon";

grant select on table "public"."transport_cities" to "anon";

grant trigger on table "public"."transport_cities" to "anon";

grant truncate on table "public"."transport_cities" to "anon";

grant update on table "public"."transport_cities" to "anon";

grant delete on table "public"."transport_cities" to "authenticated";

grant insert on table "public"."transport_cities" to "authenticated";

grant references on table "public"."transport_cities" to "authenticated";

grant select on table "public"."transport_cities" to "authenticated";

grant trigger on table "public"."transport_cities" to "authenticated";

grant truncate on table "public"."transport_cities" to "authenticated";

grant update on table "public"."transport_cities" to "authenticated";

grant delete on table "public"."transport_cities" to "service_role";

grant insert on table "public"."transport_cities" to "service_role";

grant references on table "public"."transport_cities" to "service_role";

grant select on table "public"."transport_cities" to "service_role";

grant trigger on table "public"."transport_cities" to "service_role";

grant truncate on table "public"."transport_cities" to "service_role";

grant update on table "public"."transport_cities" to "service_role";